#!/bin/bash

search=$1
isNum=false
carPlate=""
tmpFile="/tmp/output.txt"

if [ $# == 0 ]; then
  echo $0: "Usage: CM <search> (-c / -n / -f / -a)"
  exit 1
fi

if [[ $1 =~ ^[0-9]+$ ]]; then
        isNum=true
        if [ ${#1} == 7 ]; then
			search=$(echo $1 | sed 's/^/0/')
			carPlate=$(echo $1 | sed -re 's/([0-9])([0-9]{5})($|[^0-9])/\1-\2\3/' -re 's/([0-9])([0-9]{2})($|[^0-9])/\1-\2\3/')
        elif [ ${#1} == 8 ]; then
			carPlate=$(echo $1 | sed -e 's/[0-9]\{3\}/&-/g')
        fi
fi

case "$2" in
        -c)
            output=$(grep -iaw $search list.csv | awk -F"|" '{print $1, $10, $7}' | sed 's/"//g' | sort -k2 -n| uniq > $tmpFile)
			if [[ -f $tmpFile ]]; then
				years=$(awk -F" " '{print $2}' $tmpFile | sort | uniq)
				for y in $years;
				do
					count=$(awk '$2=="'$y'"' $tmpFile | sort -n | wc -l)
					echo $y - $count
				done
				echo -e "\nTotal: " $(wc -l < $tmpFile)
			else
				echo "Error: there is no results for the query"
			fi
        ;;
        -n)
            grep -iaw $search list.csv | awk -F"|" '{print $1, $10, $7}' | sed 's/"//g' | sort -k2 -n | uniq | wc -l
        ;;
        -f)
            grep -iaw $search list.csv | sed 's/"//g' | sort -t"|" -k10 -n
        ;;
        -a)
			if  [ "$isNum" = false ]; then
					echo "Please enter vaild plate number"
					exit 1;
			fi
			output=$(grep -iaw $search list.csv | sed 's/"//g')
			if ! [[ -z $output ]]; then
				year=$(echo $output | awk -F"|" '{print $10}')
				degem=$(echo $output | awk -F"|" '{print $5}')
				model=$(echo $output | awk -F"|" '{print $16}')
				gimur=$(echo $output | awk -F"|" '{print $7}')
				testu=$(echo $output | awk -F"|" '{print $13}')
				output2=$(grep -iaw $degem degem.csv | grep -iaw $year | grep -iaw "$model" | sed 's/"//g')
				if ! [[ -z "$output2" ]]; then
					kbutza=$(echo $output2 | awk -F"|" '{print $9}')
					gear=$(echo $output2 | awk -F"|" '{print $20}')
					cc=$(echo $output2 | awk -F"|" '{print $10}')
					hq=$(echo $output2 | awk -F"|" '{print $31}')
					if [ "$gear" == "0" ]; then gear="Manual"; else gear="Automatic"; fi
					if [ -z "$carPlate" ]; then carnum=$search; else carnum=$carPlate; fi
					echo -e "$model - $gimur - $cc cc - $hq hp\n$carnum\n$year\nGear: $gear\nRishoi: $kbutza\nTest until: $testu"
				else
					echo "Error: there is no results for the query"
				fi
			else
				echo "Error: there is no results for the query"
			fi
		;;
        *)
            grep -iaw $search list.csv | awk -F"|" '{print $1, $10, $7, $13}' | sed 's/"//g' | sort -k2 -n | uniq
        ;;
esac

rm -f $tmpFile
